language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - OUNIT_CI=true
addons:
  homebrew:
    update: true
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
matrix:
  include:
    - name: "debian-formats: linux"
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="debian-formats" REVDEPS=true
